/* clean_db.sql
 *
 * this will erase all player-created data in db, and *SHOULD* result in a clean install.
 *  NOTE:  this WILL NOT delete accounts.  un-comment first line to delete accounts also.
 */

-- DELETE FROM `account` WHERE 1;
DELETE FROM `alnAlliance` WHERE 1;
DELETE FROM `alnContacts` WHERE 1;
DELETE FROM `alnLabels` WHERE 1;
DELETE FROM `avatars` WHERE 1;
DELETE FROM `avatar_colors` WHERE 1;
DELETE FROM `avatar_modifiers` WHERE 1;
DELETE FROM `avatar_sculpts` WHERE 1;
DELETE FROM `billsPayable` WHERE 1;
DELETE FROM `billsReceivable` WHERE 1;
DELETE FROM `bookmarks` WHERE 1;
ALTER TABLE `bookmarks` auto_increment = 1;
DELETE FROM `bookmarkFolders` WHERE 1;
DELETE FROM `cacheOwners` WHERE 1;
DELETE FROM `channelChars` WHERE 1;
DELETE FROM `channelMods` WHERE 1;
DELETE FROM `channels` WHERE 1;
DELETE FROM `chrCharacters` WHERE 1;
ALTER TABLE `chrCharacters` auto_increment = 90000000;
DELETE FROM `chrCharacterAttributes` WHERE 1;
DELETE FROM `chrContacts` WHERE 1;
DELETE FROM `chrEmployment` WHERE 1;
DELETE FROM `chrKillTable` WHERE 1;
DELETE FROM `chrLabels` WHERE 1;
DELETE FROM `chrMissionState` WHERE 1;
DELETE FROM `chrNotes` WHERE 1;
DELETE FROM `chrOffers` WHERE 1;
DELETE FROM `chrOwnerNote` WHERE 1;
DELETE FROM `chrPausedSkillQueue` WHERE 1;
DELETE FROM `chrShipFittings` WHERE 1;
DELETE FROM `chrSkillHistory` WHERE 1;
ALTER TABLE `chrSkillHistory` auto_increment = 1;
DELETE FROM `chrSkillQueue` WHERE 1;
DELETE FROM `chrVisitedSystems` WHERE 1;
ALTER TABLE `chrVisitedSystems` auto_increment = 1;
DELETE FROM `crpAdRegistry` WHERE 1;
DELETE FROM `crpApplications` WHERE 1;
DELETE FROM `crpBulletins` WHERE 1;
DELETE FROM `crpContacts` WHERE 1;
DELETE FROM `crpCorporation` WHERE `corporationID` > 1100000;
ALTER TABLE `crpCorporation` auto_increment = 98000000;
DELETE FROM `crpLabels` WHERE 1;
DELETE FROM `crpLockedItems` WHERE 1;
DELETE FROM `crpItemEvent` WHERE 1;
DELETE FROM `crpRecruiters` WHERE 1;
DELETE FROM `crpRoleHistroy` WHERE 1;
DELETE FROM `crpRoleTitles` WHERE 1;
DELETE FROM `crpShares` WHERE 1;
DELETE FROM `crpVoteItems` WHERE 1;
DELETE FROM `crpWalletDivisons` WHERE 1;
DELETE FROM `droneState` WHERE 1;
DELETE FROM `dunActive` WHERE 1;
DELETE FROM `entity` WHERE 1;
ALTER TABLE `entity` auto_increment = 140000000;
DELETE FROM `entity_attributes` WHERE 1;
DELETE FROM `eveMail` WHERE 1;
DELETE FROM `eveMailDetails` WHERE 1;
DELETE FROM `eveStaticOwners` WHERE `ownerID`> 90000000;
DELETE FROM `invBlueprints` WHERE 1;
DELETE FROM `jnlCharacters` WHERE 1;
DELETE FROM `jnlCorporations` WHERE 1;
DELETE FROM `mailLabel` WHERE 1;
DELETE FROM `mailList` WHERE 1;
DELETE FROM `mailListUsers` WHERE 1;
DELETE FROM `mailMessage` WHERE 1;
DELETE FROM `mailStatus` WHERE 1;
DELETE FROM `mapDynamicData` WHERE 1;
DELETE FROM `mktHistory` WHERE 1;
DELETE FROM `mktOrders` WHERE 1;
ALTER TABLE `mktOrders` auto_increment = 1;
DELETE FROM `mktTransactions` WHERE 1;
DELETE FROM `piCCPin` WHERE 1;
DELETE FROM `piECUHeads` WHERE 1;
DELETE FROM `piLaunches` WHERE 1;
DELETE FROM `piLinks` WHERE 1;
DELETE FROM `piPinContents` WHERE 1;
DELETE FROM `piPins` WHERE 1;
DELETE FROM `piPlanets` WHERE 1;
DELETE FROM `piRoutes` WHERE 1;
DELETE FROM `posCustomOfficeData` WHERE 1;
DELETE FROM `posJumpBridgeData` WHERE 1;
DELETE FROM `posStructureData` WHERE 1;
DELETE FROM `posTowerData` WHERE 1;
DELETE FROM `ramJobs` WHERE 1;
DELETE FROM `rentalInfo` WHERE 1;
DELETE FROM `repStandingChanges` WHERE 1;
DELETE FROM `repStandings` WHERE toID > 90000000;
DELETE FROM `repStandings` WHERE fromID > 90000000;
DELETE FROM `shipInsurance` WHERE 1;
DELETE FROM `srvStatisticData` WHERE 1;
DELETE FROM `srvStatisticDataHistory` WHERE 1;
DELETE FROM `staOffices` WHERE 1;
DELETE FROM `sysAsteroids` WHERE 1;
DELETE FROM `sysSignatures` WHERE 1;
DELETE FROM `webBounties` WHERE 1;