-- MySQL dump 10.13  Distrib 5.1.41, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: evemu
-- ------------------------------------------------------
-- Server version	5.1.41-3ubuntu12.10

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `liveupdates`
--

DROP TABLE IF EXISTS `liveupdates`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `liveupdates` (
  `updateID` int(11) NOT NULL DEFAULT '0',
  `updateName` varchar(100) DEFAULT NULL,
  `description` varchar(100) DEFAULT NULL,
  `machoVersionMin` int(11) DEFAULT NULL,
  `machoVersionMax` int(11) DEFAULT NULL,
  `buildNumberMin` int(11) DEFAULT NULL,
  `buildNumberMax` int(11) DEFAULT NULL,
  `methodName` varchar(100) DEFAULT NULL,
  `objectID` varchar(100) DEFAULT NULL,
  `codeType` varchar(100) DEFAULT NULL,
  `code` blob,
  PRIMARY KEY (`updateID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `liveupdates`
--

LOCK TABLES `liveupdates` WRITE;
/*!40000 ALTER TABLE `liveupdates` DISABLE KEYS */;
INSERT INTO `liveupdates` VALUES
(0, 'PhotoUpload','Generated by liveupdategen',1,330,1,500000,'AskForPortraitConfirmation','uicls.CharacterCreationLayer::CharacterCreationLayer','globalClassMethod','c\0\0\0\0\0\0\0\0\0G\0\0\0s∫\0\0\0|\0\0j\0\0É\0\0}\0|\0\0j\0|\0\0j\0É\0}\0t\0|\0d\0É\0}\0|\0j\0É\0\0}\0|\0j\0É\0\0t\0j\0d\0i\0d\0d\06É\0t\0j \0d\0É\0}\0|\0d\0\0k\0sÅ\0|\0t\0k\0rõ\0t\0j\0d\0i\0d\0d\06É\0n\0t\0j\0d\0i\0d\0d\06É\0t\0Sd\0\0S(\0\0\0Nt\0\0\0rbt\0\0\0CustomNotifys*\0\0\0Uploading your character portrait to EVEMut\0\0\0notifyt\0\0\0photoUploadSvcs\0\0\0Portrait upload failed!s\0\0\0Portrait upload successful!(\r\0\0\0t\0\0\0GetActivePortraitt\0\0\0GetPortraitSnapshotPatht\0\0\0activePortraitIndext\0\0\0opent\0\0\0readt\0\0\0closet\0\0\0evet\0\0\0Messaget\0\0\0smt \0\0\0RemoteSvct\0\0\0Nonet\0\0\0Falset\0\0\0True(\0\0\0t\0\0\0selft\0\0\0argst\0\0\0photot\0\0\0snapPatht  \0\0\0photoFilet    \0\0\0photoDatat\0\0\0result(\0\0\0\0(\0\0\0\0s\0\0\0<string>t\Z\0\0\0AskForPortraitConfirmation\0\0\0s\0\0\0\0\n\Z')
(1, 'GetTutorials', 'Generated by liveupdategen', 1, 330, 1, 500000, 'GetTutorials', 'svc.tutorial::TutorialSvc', 'globalClassMethod', 0x6301000000020000000500000043000000735d0000006401006400006c00007d01007401006a020064020069010064030064040036830200017c01006a03006a04006405008301006a0500640600640700640800830300017401006a0200640200690100640900640400368302000169000053280a0000004e69ffffffff740c000000437573746f6d4e6f74696679731300000044697361626c696e67207475746f7269616c7374060000006e6f7469667974040000006368617274020000007569740d00000073686f775475746f7269616c73690000000073130000005475746f7269616c732064697361626c6564212806000000740b0000005f5f6275696c74696e5f5f740300000065766574070000004d657373616765740800000073657474696e6773740300000047657474030000005365742802000000740400000073656c6652050000002800000000280000000073080000003c737472696e673e740c0000004765745475746f7269616c7303000000730a00000000010c0117011f011701);

/*!40000 ALTER TABLE `liveupdates` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2011-12-16 11:10:11
