# EVEmu Log Settings:
#  Log Version: 7.3

#  NOTE  not all of these actually work yet (or make sense), most notabably are *INFOs, *TRACEs, *MESSAGEs and *WARNINGs
# ALSO NOTE:    msg levels of "Message" and (numerically) higher are noisy, with each higher level generating more data

 #  1 - error
 #  2 - warning
 #  3 - message
 #  4 - debug
 #  5 - info
 #  6 - trace

# Debug Logging:
DEBUG=0
DEBUG__DEBUG=0

# Network Activity Logging:
NET=0
NET__PRES_ERROR=1
NET__PRES_DEBUG=0
NET__PRES_TRACE=0
NET__PRES_REP=0
NET__PRES_RAW=0
NET__PRES_REP_OUT=0
NET__PRES_RAW_OUT=0
NET__MARSHAL_ERROR=1
NET__MARSHAL_TRACE=0
NET__UNMARSHAL_TRACE=0
NET__UNMARSHAL_BUFHEX=0
NET__UNMARSHAL_ERROR=1
NET__ZEROINFL=0
NET__ZEROCOMP=0
NET__PACKET_ERROR=1
NET__PACKET_WARNING=0
NET__DISPATCH_ERROR=1

# Packet Collection Logging:
COLLECT=0
COLLECT__MESSAGE=0
COLLECT__ERROR=1
COLLECT__ERROR_DETAIL=0
COLLECT__TCP=0
COLLECT__RAW_HEX=0
COLLECT__PYREP_DUMP=0
COLLECT__PACKET_DUMP=0
COLLECT__PACKET_SRC=0
COLLECT__PACKET_DEST=0
COLLECT__CALL_SUMMARY=0
COLLECT__DESTINY=0
COLLECT__DESTINY_REP=0
COLLECT__DESTINY_HEX=0
COLLECT__CALL_DUMP=0
COLLECT__NOTIFY_SUMMARY=0
COLLECT__NOTIFY_DUMP=0
# bind and bind_dumps are in COLLECT__OTHER_DUMP
COLLECT__OTHER_DUMP=0
COLLECT__CALL_XML=0
COLLECT__CALLRSP_XML=0
COLLECT__NOTIFY_XML=0
COLLECT__MISC_XML=0
COLLECT__CALLRSP_SQL=0

# Service Logging:
SERVICE=0
SERVICE__ERROR=1
SERVICE__WARNING=0
SERVICE__CALLS=0
# bind requests with piggyback calls are noted in SERVICE__MESSAGE
SERVICE__MESSAGE=0
SERVICE__CALL_TRACE=0
SERVICE__CALL_DUMP=0

# Cosmic Mgr Logging:
COSMIC_MGR=0
COSMIC_MGR__ERROR=1
COSMIC_MGR__WARNING=0
COSMIC_MGR__MESSAGE=0
COSMIC_MGR__DEBUG=0
COSMIC_MGR__TRACE=0

# Planet Logging:
PLANET=0
# pin creation fail msgs in PLANET__MESSAGE
PLANET__ERROR=1
PLANET__WARNING=0
# pin creation success msgs in PLANET__MESSAGE
PLANET__MESSAGE=0
PLANET__DEBUG=0
# planet bind and dumps in PLANET__INFO
PLANET__INFO=0
# command loops and various call traces reported in PLANET__TRACE
PLANET__TRACE=0
# planet-specific call dumps in PLANET__DUMP
PLANET__DUMP=0
# get colony return dumps in PLANET__GC_DUMP
PLANET__GC_DUMP=0

# Effects Logging:
EFFECTS=0
EFFECTS__ERROR=1
EFFECTS__WARNING=0
EFFECTS__MESSAGE=0
EFFECTS__DEBUG=0
EFFECTS__TRACE=0

# Bulk Logging:
BULKDATA=1
BULKDATA__ERROR=1
BULKDATA__WARNING=0
BULKDATA__MESSAGE=0
BULKDATA__DEBUG=0
BULKDATA__INFO=0
BULKDATA__TRACE=0
BULKDATA__DUMP=0

# Cache Logging:
CACHE=0
CACHE__ERROR=1
CACHE__WARNING=0
CACHE__MESSAGE=0
CACHE__DEBUG=0
CACHE__INFO=0
CACHE__TRACE=0
CACHE__DUMP=0

# AutoPilot Logging:
AUTOPILOT=1
AUTOPILOT__ERROR=1
AUTOPILOT__WARNING=0
AUTOPILOT__MESSAGE=0
AUTOPILOT__DEBUG=0
AUTOPILOT__INFO=0
AUTOPILOT__TRACE=0

# Mail Logging:
MAIL=0
MAIL__ERROR=1
MAIL__WARNING=0
MAIL__MESSAGE=0
MAIL__DEBUG=0
MAIL__INFO=0
MAIL__TRACE=0
MAIL__DUMP=0

# Corporation Logging:
CORP=0
CORP__ERROR=1
CORP__WARNING=0
CORP__INFO=0
CORP__MESSAGE=0
CORP__TRACE=0
CORP__CALL=0
CORP__CALL_DUMP=0
CORP__DB_ERROR=1
CORP__DB_WARNING=0
CORP__DB_INFO=0
CORP__DB_MESSAGE=0

# Inventory Logging:
INV=0
INV__ERROR=1
INV__WARNING=0
#inventory LoadContents() and wreck empty msgs in INV__INFO
INV__INFO=0
#inventory calls in INV__MESSAGE
INV__MESSAGE=0
#item add/remove into inventory msgs in INV__TRACE
INV__TRACE=0
#inventory bind req in INV__INFO
INV__BIND=0
#inventory bind dump in INV__INFO
INV__DUMP=0

# Spawn Logging:
SPAWN=0
SPAWN__ERROR=1
SPAWN__WARNING=0
SPAWN__MESSAGE=0
SPAWN__POP=0
SPAWN__DEPOP=0
# details on creating, adding, and checking spawn maps
SPAWN__TRACE=0

# Item Logging:
ITEM=0
ITEM__ERROR=1
ITEM__WARNING=0
ITEM__MESSAGE=0
# item attrib count displayed when attribs loaded in ITEM__DEBUG
ITEM__DEBUG=0
# item creation msgs sent in ITEM__TRACE
ITEM__TRACE=0

# NPC Logging:
NPC=0
NPC__ERROR=1
NPC__WARNING=0
# npc warpto msgs in NPC__MESSAGE
NPC__MESSAGE=0
NPC__INFO=0
NPC__TRACE=0
NPC__AI_TRACE=0

# Concord Logging:
CONCORD=0
CONCORD__ERROR=1
CONCORD__WARNING=0
CONCORD__MESSAGE=0
CONCORD__INFO=0
CONCORD__TRACE=0
CONCORD__AI_TRACE=0

# Agent Logging:
AGENT=0
AGENT__ERROR=1
AGENT__WARNING=0
AGENT__MESSAGE=0
AGENT__DEBUG=0
AGENT__INFO=0
AGENT__TRACE=0

# Market Logging:
MARKET=0
MARKET__ERROR=1
MARKET__WARNING=0
MARKET__MESSAGE=0
MARKET__DEBUG=0
MARKET__TRACE=0

# Mining Logging:
MINING=0
MINING__ERROR=1
MINING__WARNING=0
MINING__MESSAGE=0
MINING__INFO=0
MINING__DEBUG=0
# module attrib setting/creation msgs displayed in MINING__TRACE
MINING__TRACE=0

# Manufacturing Logging:
MANUF=0
MANUF__ERROR=1
MANUF__WARNING=0
MANUF__MESSAGE=0
MANUF__INFO=0
MANUF__DEBUG=0
MANUF__TRACE=0
MANUF__DUMP=0

# Destiny Logging:
DESTINY=0
DESTINY__ERROR=1
DESTINY__WARNING=0
# SendSetState, SlimItem, AddBalls and RemoveBalls message in DESTINY__MESSAGE  * NOISY *
DESTINY__MESSAGE=0
# SlimItem dumps in DESTINY__DEBUG  ** NOISY **
DESTINY__DEBUG=0
# dock range and BubbleList reported in DESTINY__TRACE
DESTINY__TRACE=0
# some destiny update msgs sent in DESTINY__UPDATES
DESTINY__UPDATES=0
#DESTINY__UPDATES_DUMP=0
# AddBall packet dump in DESTINY__BALL_DUMP
DESTINY__BALL_DUMP=0
# AddBall packet decoded in DESTINY__BALL_DECODE
DESTINY__BALL_DECODE=0
# SetState packet dump in DESTINY__SETSTATE  *** VERY NOISY ***
DESTINY__SETSTATE=0
# SetState decoded in DESTINY__SETSTATE_DECODE
DESTINY__SETSTATE_DECODE=0
# SystemBubble calls in DESTINY__BUBBLE_DEBUG
DESTINY__BUBBLE_DEBUG=0
# BubbleManager calls in DESTINY__BUBBLE_TRACE
DESTINY__BUBBLE_TRACE=0
#  ***  these next 6 reports output data that increases linearily with amount of objects moving  ***
# Destiny BubbleCast msgs in DESTINY__BUBBLECAST  * NOISY *
DESTINY__BUBBLECAST=0
# Destiny BubbleCast msgs dumped in DESTINY__BUBBLECAST_DUMP  ** NOISY **
DESTINY__BUBBLECAST_DUMP=0
# move data reported in DESTINY__MOVE_TRACE
DESTINY__MOVE_TRACE=0
# turn data reported in DESTINY__TURN_TRACE
DESTINY__TURN_TRACE=0
# orbit data reported in DESTINY__ORBIT_TRACE
DESTINY__ORBIT_TRACE=0
# warp data reported in DESTINY__ORBIT_TRACE
DESTINY__WARP_TRACE=0

# Physics Logging:
PHYSICS=0
# target = null when turning reported in PHYSICS__ERROR   <--  this makes no sense...change it.
PHYSICS__ERROR=1
# not used
PHYSICS__WARNING=0
# not used
PHYSICS__MESSAGE=0
# not used
PHYSICS__INFO=0
# ship wreck position reporting in PHYSICS__TRACE
PHYSICS__TRACE=0
# not used
PHYSICS__TRACEPOS=0

# Common Logging:
COMMON=0
COMMON__ERROR=1
# warning also for EncodeDestiny() and MakeSlimItem() calls.
COMMON__WARNING=0
COMMON__INFO=0
COMMON__MESSAGE=0
COMMON__PYREP=0

# Server Logging:
SERVER=0
SERVER__INIT=0
SERVER__INIT_ERR=0
SERVER__CLIENTS=0
# memory usage reported on StatSave() calls using SERVER__INFO
SERVER__INFO=0
SERVER__SHUTDOWN=0

# Command Logging:
COMMAND=0
COMMAND__ERROR=1
COMMAND__MESSAGE=0

# Ship Logging:
SHIP=0
SHIP__ERROR=1
# Pilot 'errors' in SHIP__WARNING
SHIP__WARNING=0
# Ship Process data in SHIP__MESSAGE (shield/cap recharge)
SHIP__MESSAGE=0
# Ship EncodeDestiny, SE creating and DNA msgs in SHIP__INFO
SHIP__INFO=0
# Ship hold capacities displayed in SHIP__TRACE
SHIP__TRACE=0
SHIP__MODULE_ERROR=1
# Charge not found reported in SHIP__MODULE_WARNING
SHIP__MODULE_WARNING=0
# Mod Online/Offline warnings reported in SHIP__MODULE_MESSAGE
SHIP__MODULE_MESSAGE=0
# Mod timer setting and Effects msgs reported in SHIP__MODULE_TRACE
SHIP__MODULE_TRACE=0
# Mod Create/Populate and Undocking "OnlineModules" list dumped in SHIP__MODULE_INFO
SHIP__MODULE_INFO=0
SHIP__MODULE_DEBUG=0

# Target Logging:
TARGET=0
TARGET__ERROR=1
TARGET__WARNING=0
# Target Add/Remove and turrent calculation msgs in TARGET__MESSAGE
TARGET__MESSAGE=0
# TargMgr creating and target lock msgs given in TARGET__INFO
TARGET__INFO=0
# target ignore msgs given in TARGET__DEBUG
TARGET__DEBUG=0
TARGET__TRACE=0
# target dumping only works on test server (as set in eve-server.xml)
TARGET__DUMP=0

# Damage Logging:
DAMAGE=1
DAMAGE__ERROR=1
DAMAGE__WARNING=1
# Drone damage Init and SE damage updates given in DAMAGE__MESSAGE
DAMAGE__MESSAGE=0
# damage notif and s/a/h depleted given in DAMAGE__INFO
DAMAGE__INFO=0
# PC damage Init and damage calc's given in DAMAGE__TRACE
DAMAGE__TRACE=0
# NPC damage Init and damage calc's given in DAMAGE__TRACE_NPC
DAMAGE__TRACE_NPC=0
# damage applied to s/a/h in DAMAGE__DEBUG
DAMAGE__DEBUG=0

# LSC Logging:
LSC=0
LSC__ERROR=1
LSC__WARNING=0
LSC__MESSAGE=0
LSC__INFO=0
LSC__CHANNELS=0

# LP Logging:
LP=0
LP__ERROR=1
LP__WARNING=0
LP__MESSAGE=0
LP__INFO=0
LP__DEBUG=0

# Character Logging:
CHARACTER=0
CHARACTER__ERROR=1
CHARACTER__WARNING=0
CHARACTER__MESSAGE=0
CHARACTER__INFO=0
CHARACTER__DEBUG=0
CHARACTER__TRACE=0
CHARACTER__BIND=0
# skill msgs in CHARACTER__SKILL_TRACE
CHARACTER__SKILL_TRACE=0

# Client Logging:
CLIENT=0
CLIENT__ERROR=1
CLIENT__WARNING=0
CLIENT__MESSAGE=0
# GetAllInfo is dumped in CLIENT__INFO
CLIENT__INFO=0
#all calls logged in CLIENT__CALL_REP
CLIENT__CALL_REP=0
CLIENT__CALL_DUMP=0
CLIENT__IN_ALL=0
CLIENT__OUT_ALL=0
# notifications sending msgs in CLIENT__NOTIFY_REP  *** VERY NOISY ***
CLIENT__NOTIFY_REP=0
# Notifications dumped in CLIENT__NOTIFY_DUMP  * NOISY *
CLIENT__NOTIFY_DUMP=0
# CLIENT__QUEUE_DUMP dumps everything in _SendQueuedUpdates()  ** VERY NOISY **
CLIENT__QUEUE_DUMP=0
# Session Change updates dumped in CLIENT__SESSION  * NOISY *
CLIENT__SESSION=0
# SendAttributeChanges (and others) dumped in CLIENT__TRACE  ** NOISY **
CLIENT__TRACE=0
# tells client to send stack traces of internal exceptions and displays on console (exception displaying)
CLIENT__STACK_TRACE=0
# Process timer msgs in CLIENT__TIMER
CLIENT__TIMER=1
CLIENT__TEXT=0

# Player Logging:
PLAYER=0
PLAYER__ERROR=1
# MoveToLocation and "Item Owner not found" msgs in PLAYER__WARNING
PLAYER__WARNING=0
# CreateShipSE msgs in PLAYER__MESSAGE
PLAYER__MESSAGE=0
# Add/Remove to/from player count
PLAYER__INFO=0
# Add/Remove to/from system mgr
PLAYER__TRACE=0
PLAYER__AP_TRACE=0
# All Trade msgs in PLAYER__TRADE_MESSAGE
PLAYER__TRADE_MESSAGE=0

# TCP Server Logging:
TCP_SERVER=0
TCP_SERVER__ERROR=1
TCP_SERVER__WARNING=0
TCP_SERVER__MESSAGE=0
TCP_SERVER__INFO=0
TCP_SERVER__TRACE=0

# TCP Client Logging:
TCP_CLIENT=0
TCP_CLIENT__ERROR=1
TCP_CLIENT__WARNING=0
TCP_CLIENT__MESSAGE=0
TCP_CLIENT__INFO=0
TCP_CLIENT__TRACE=0

# Database Logging:
DATABASE=0
DATABASE__ERROR=1
DATABASE__MESSAGE=0
DATABASE__INFO=0
# DATABASE__QUERIES prints out every query to db (console spam)  *** VERY NOISY ***
DATABASE__QUERIES=0
# DATABASE__RESULTS prints out count of columns returned for querys that return lists of items  * NOISY *
DATABASE__RESULTS=0
DATABASE__ALL_ERRORS=1
DATABASE__PACKED=0

# Thread Logging:
THREAD=0
THREAD__ERROR=1
# CreateThreads() shown in THREAD__WARNING
THREAD__WARNING=0
# EndThreads() is shown in THREAD__MESSAGE
THREAD__MESSAGE=0
# Add() and Remove() are in THREAD__INFO
THREAD__INFO=0
# EndThreads() prints specific threadIDs joined in THREAD__TRACE
THREAD__TRACE=0

