
 /**
  * @name EVE_Damage.h
  *     Damage Notifications and other notes for Alasiya EvEmu
  *
  * @Author:        Allan
  * @date:          2 January 2018
  *
  */


#ifndef EVE_DAMAGE_H
#define EVE_DAMAGE_H


/*  these are based on client settings of damage notification.
 * msg packets are
 *   " "  - to others
 *   "R"  - received
 *   "RD  - received with details
 */

/*{'messageKey': 'AttackHit1', 'dataID': 17885829, 'suppressable': False, 'bodyID': 260383, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 114}
 * {'messageKey': 'AttackHit1Banked', 'dataID': 17878336, 'suppressable': False, 'bodyID': 257589, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2641}
 * {'messageKey': 'AttackHit1Banked_Simple', 'dataID': 17878333, 'suppressable': False, 'bodyID': 257588, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2652}
 * {'messageKey': 'AttackHit1R', 'dataID': 17885835, 'suppressable': False, 'bodyID': 260385, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 115}
 * {'messageKey': 'AttackHit1RD', 'dataID': 17885838, 'suppressable': False, 'bodyID': 260386, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 116}
 * {'messageKey': 'AttackHit1RD_Simple', 'dataID': 17879270, 'suppressable': False, 'bodyID': 257946, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2352}
 * {'messageKey': 'AttackHit1R_Simple', 'dataID': 17879273, 'suppressable': False, 'bodyID': 257947, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2367}
 * {'messageKey': 'AttackHit1_Simple', 'dataID': 17879276, 'suppressable': False, 'bodyID': 257948, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2361}
 * {'messageKey': 'AttackHit2', 'dataID': 17885841, 'suppressable': False, 'bodyID': 260387, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 117}
 * {'messageKey': 'AttackHit2Banked', 'dataID': 17878339, 'suppressable': False, 'bodyID': 257590, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2642}
 * {'messageKey': 'AttackHit2Banked_Simple', 'dataID': 17878330, 'suppressable': False, 'bodyID': 257587, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2653}
 * {'messageKey': 'AttackHit2R', 'dataID': 17885844, 'suppressable': False, 'bodyID': 260388, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 118}
 * {'messageKey': 'AttackHit2RD', 'dataID': 17885850, 'suppressable': False, 'bodyID': 260390, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 119}
 * {'messageKey': 'AttackHit2RD_Simple', 'dataID': 17879279, 'suppressable': False, 'bodyID': 257949, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2353}
 * {'messageKey': 'AttackHit2R_Simple', 'dataID': 17879282, 'suppressable': False, 'bodyID': 257950, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2368}
 * {'messageKey': 'AttackHit2_Simple', 'dataID': 17879285, 'suppressable': False, 'bodyID': 257951, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2362}
 * {'messageKey': 'AttackHit3', 'dataID': 17885853, 'suppressable': False, 'bodyID': 260391, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 120}
 * {'messageKey': 'AttackHit3Banked', 'dataID': 17878342, 'suppressable': False, 'bodyID': 257591, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2644}
 * {'messageKey': 'AttackHit3Banked_Simple', 'dataID': 17878327, 'suppressable': False, 'bodyID': 257586, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2654}
 * {'messageKey': 'AttackHit3R', 'dataID': 17885856, 'suppressable': False, 'bodyID': 260392, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 121}
 * {'messageKey': 'AttackHit3RD', 'dataID': 17885859, 'suppressable': False, 'bodyID': 260393, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 122}
 * {'messageKey': 'AttackHit3RD_Simple', 'dataID': 17879288, 'suppressable': False, 'bodyID': 257952, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2354}
 * {'messageKey': 'AttackHit3R_Simple', 'dataID': 17879291, 'suppressable': False, 'bodyID': 257953, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2369}
 * {'messageKey': 'AttackHit3_Simple', 'dataID': 17879294, 'suppressable': False, 'bodyID': 257954, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2363}
 * {'messageKey': 'AttackHit4', 'dataID': 17885862, 'suppressable': False, 'bodyID': 260394, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 123}
 * {'messageKey': 'AttackHit4Banked', 'dataID': 17878345, 'suppressable': False, 'bodyID': 257592, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2645}
 * {'messageKey': 'AttackHit4Banked_Simple', 'dataID': 17878318, 'suppressable': False, 'bodyID': 257583, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2655}
 * {'messageKey': 'AttackHit4R', 'dataID': 17885865, 'suppressable': False, 'bodyID': 260395, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 124}
 * {'messageKey': 'AttackHit4RD', 'dataID': 17885868, 'suppressable': False, 'bodyID': 260396, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 125}
 * {'messageKey': 'AttackHit4RD_Simple', 'dataID': 17879297, 'suppressable': False, 'bodyID': 257955, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2355}
 * {'messageKey': 'AttackHit4R_Simple', 'dataID': 17879300, 'suppressable': False, 'bodyID': 257956, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2370}
 * {'messageKey': 'AttackHit4_Simple', 'dataID': 17879303, 'suppressable': False, 'bodyID': 257957, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2364}
 * {'messageKey': 'AttackHit5', 'dataID': 17885871, 'suppressable': False, 'bodyID': 260397, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 126}
 * {'messageKey': 'AttackHit5Banked', 'dataID': 17878348, 'suppressable': False, 'bodyID': 257593, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2646}
 * {'messageKey': 'AttackHit5Banked_Simple', 'dataID': 17878324, 'suppressable': False, 'bodyID': 257585, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2657}
 * {'messageKey': 'AttackHit5R', 'dataID': 17885874, 'suppressable': False, 'bodyID': 260398, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 127}
 * {'messageKey': 'AttackHit5RD', 'dataID': 17885877, 'suppressable': False, 'bodyID': 260399, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 128}
 * {'messageKey': 'AttackHit5RD_Simple', 'dataID': 17879306, 'suppressable': False, 'bodyID': 257958, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2356}
 * {'messageKey': 'AttackHit5R_Simple', 'dataID': 17879309, 'suppressable': False, 'bodyID': 257959, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2371}
 * {'messageKey': 'AttackHit5_Simple', 'dataID': 17879312, 'suppressable': False, 'bodyID': 257960, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2365}
 * {'messageKey': 'AttackHit6', 'dataID': 17885880, 'suppressable': False, 'bodyID': 260400, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 129}
 * {'messageKey': 'AttackHit6Banked', 'dataID': 17878351, 'suppressable': False, 'bodyID': 257594, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2647}
 * {'messageKey': 'AttackHit6Banked_Simple', 'dataID': 17878321, 'suppressable': False, 'bodyID': 257584, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2658}
 * {'messageKey': 'AttackHit6R', 'dataID': 17885883, 'suppressable': False, 'bodyID': 260401, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 130}
 * {'messageKey': 'AttackHit6RD', 'dataID': 17885886, 'suppressable': False, 'bodyID': 260402, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 131}
 * {'messageKey': 'AttackHit6RD_Simple', 'dataID': 17879315, 'suppressable': False, 'bodyID': 257961, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2357}
 * {'messageKey': 'AttackHit6R_Simple', 'dataID': 17879318, 'suppressable': False, 'bodyID': 257962, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2372}
 * {'messageKey': 'AttackHit6_Simple', 'dataID': 17879321, 'suppressable': False, 'bodyID': 257963, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2366}
 * {'messageKey': 'AttackMiss1', 'dataID': 17885907, 'suppressable': False, 'bodyID': 260410, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 135}
 * {'messageKey': 'AttackMiss1Banked', 'dataID': 17878555, 'suppressable': False, 'bodyID': 257671, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2648}
 * {'messageKey': 'AttackMiss1Banked_Simple', 'dataID': 17878563, 'suppressable': False, 'bodyID': 257674, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2660}
 * {'messageKey': 'AttackMiss1R', 'dataID': 17885910, 'suppressable': False, 'bodyID': 260411, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 136}
 * {'messageKey': 'AttackMiss1RD', 'dataID': 17885913, 'suppressable': False, 'bodyID': 260412, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 137}
 * {'messageKey': 'AttackMiss1RD_Simple', 'dataID': 17879536, 'suppressable': False, 'bodyID': 258044, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2358}
 * {'messageKey': 'AttackMiss1R_Simple', 'dataID': 17879539, 'suppressable': False, 'bodyID': 258045, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2373}
 * {'messageKey': 'AttackMiss1_Simple', 'dataID': 17879474, 'suppressable': False, 'bodyID': 258022, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2376}
 * {'messageKey': 'AttackMiss2', 'dataID': 17885916, 'suppressable': False, 'bodyID': 260413, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 138}
 * {'messageKey': 'AttackMiss2Banked', 'dataID': 17878571, 'suppressable': False, 'bodyID': 257677, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2649}
 * {'messageKey': 'AttackMiss2Banked_Simple', 'dataID': 17878383, 'suppressable': False, 'bodyID': 257606, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2661}
 * {'messageKey': 'AttackMiss2R', 'dataID': 17885919, 'suppressable': False, 'bodyID': 260414, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 139}
 * {'messageKey': 'AttackMiss2RD', 'dataID': 17885927, 'suppressable': False, 'bodyID': 260417, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 140}
 * {'messageKey': 'AttackMiss2RD_Simple', 'dataID': 17879542, 'suppressable': False, 'bodyID': 258046, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2359}
 * {'messageKey': 'AttackMiss2R_Simple', 'dataID': 17879554, 'suppressable': False, 'bodyID': 258050, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2374}
 * {'messageKey': 'AttackMiss2_Simple', 'dataID': 17879551, 'suppressable': False, 'bodyID': 258049, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2377}
 * {'messageKey': 'AttackMiss3', 'dataID': 17885930, 'suppressable': False, 'bodyID': 260418, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 141}
 * {'messageKey': 'AttackMiss3Banked', 'dataID': 17878574, 'suppressable': False, 'bodyID': 257678, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2650}
 * {'messageKey': 'AttackMiss3Banked_Simple', 'dataID': 17878482, 'suppressable': False, 'bodyID': 257642, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2662}
 * {'messageKey': 'AttackMiss3R', 'dataID': 17885933, 'suppressable': False, 'bodyID': 260419, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 142}
 * {'messageKey': 'AttackMiss3RD', 'dataID': 17885936, 'suppressable': False, 'bodyID': 260420, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 143}
 * {'messageKey': 'AttackMiss3RD_Simple', 'dataID': 17879557, 'suppressable': False, 'bodyID': 258051, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2360}
 * {'messageKey': 'AttackMiss3R_Simple', 'dataID': 17879548, 'suppressable': False, 'bodyID': 258048, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2375}
 * {'messageKey': 'AttackMiss3_Simple', 'dataID': 17879545, 'suppressable': False, 'bodyID': 258047, 'messageType': 'notify', 'urlAudio': '', 'urlIcon': '', 'titleID': None, 'messageID': 2378}
 *
 * {'FullPath': u'UI/Messages', 'messageID': 257946, 'label': u'AttackHit1RD_SimpleBody'}(u'<color=0xffbb6600>{owner} ({[item]weapon.name}) hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257583, 'label': u'AttackHit4Banked_SimpleBody'}(u'<color=0xff99bb00>Group of {[item]weapon.name} strikes {target} for <b>{[numeric]damage, decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage, decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257957, 'label': u'AttackHit4_SimpleBody'}(u'<color=0xff99bb00>{[item]weapon.name} hits {target} for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257963, 'label': u'AttackHit6_SimpleBody'}(u'<color=0xff99bb00>{[item]weapon.name} hits {target} for <b>{[numeric]damage,decimalPlaces=0}</b> damage (Wrecking!)', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258044, 'label': u'AttackMiss1RD_SimpleBody'}(u'{owner} ({[item]weapon.name}) misses you', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258045, 'label': u'AttackMiss1R_SimpleBody'}(u'{source} misses you', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258046, 'label': u'AttackMiss2RD_SimpleBody'}(u'{owner} ({[item]weapon.name}) misses you', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258047, 'label': u'AttackMiss3_SimpleBody'}(u'{[item]weapon.name} misses {target}', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258048, 'label': u'AttackMiss3R_SimpleBody'}(u'{source} misses you', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258049, 'label': u'AttackMiss2_SimpleBody'}(u'{[item]weapon.name} misses {target}', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258050, 'label': u'AttackMiss2R_SimpleBody'}(u'{source} misses you', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258051, 'label': u'AttackMiss3RD_SimpleBody'}(u'{owner} ({[item]weapon.name}) misses you', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257584, 'label': u'AttackHit6Banked_SimpleBody'}(u'<color=0xff99bb00>Group of {[item]weapon.name} strikes {target} for <b>{[numeric]damage, decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage, decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257585, 'label': u'AttackHit5Banked_SimpleBody'}(u'<color=0xff99bb00>Group of {[item]weapon.name} strikes {target} for <b>{[numeric]damage, decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage, decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257586, 'label': u'AttackHit3Banked_SimpleBody'}(u'<color=0xff99bb00>Group of {[item]weapon.name} strikes {target} for <b>{[numeric]damage, decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage, decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257587, 'label': u'AttackHit2Banked_SimpleBody'}(u'<color=0xff66bb00>Group of {[item]weapon.name} strikes {target} for <b>{[numeric]damage, decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage, decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257588, 'label': u'AttackHit1Banked_SimpleBody'}(u'<color=0xff99bb00>Group of {[item]weapon.name} strikes {target} for <b>{[numeric]damage, decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage, decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257589, 'label': u'AttackHit1BankedBody'}(u'<color=0xffbbbb00>Your group of {[item]weapon.name} barely scratches {target}, causing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257590, 'label': u'AttackHit2BankedBody'}(u'<color=0xffbbbb00>Your group of {[item]weapon.name} lightly hits {target}, doing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257591, 'label': u'AttackHit3BankedBody'}(u'<color=0xffbbbb00>Your group of {[item]weapon.name} hits {target}, doing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257592, 'label': u'AttackHit4BankedBody'}(u'<color=0xffbbbb00>Your group of {[item]weapon.name} is well aimed at {target}, inflicting {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257593, 'label': u'AttackHit5BankedBody'}(u'<color=0xffbbbb00>Your group of {[item]weapon.name} places an excellent hit on {target}, inflicting {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257594, 'label': u'AttackHit6BankedBody'}(u'<color=0xffbbbb00>Your group of {[item]weapon.name} perfectly strikes {target}, wrecking for {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257606, 'label': u'AttackMiss2Banked_SimpleBody'}(u'Group of {[item]weapon.name} misses {target}', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257642, 'label': u'AttackMiss3Banked_SimpleBody'}(u'Group of {[item]weapon.name} miss {target}.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257671, 'label': u'AttackMiss1BankedBody'}(u'Your group of {[item]weapon.name} misses {target} completely.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257674, 'label': u'AttackMiss1Banked_SimpleBody'}(u'Group of {[item]weapon.name} miss {target}', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257677, 'label': u'AttackMiss2BankedBody'}(u'Your group of {[item]weapon.name} barely misses {target}.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257678, 'label': u'AttackMiss3BankedBody'}(u'Your group of {[item]weapon.name} glances off {target}, causing no real damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257947, 'label': u'AttackHit1R_SimpleBody'}(u'<color=0xffbb6600>{source} hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage\r\n\r\n', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257948, 'label': u'AttackHit1_SimpleBody'}(u'<color=0xff99bb00>{[item]weapon.name} hits {target} for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257949, 'label': u'AttackHit2RD_SimpleBody'}(u'<color=0xffbb6600>{owner} ({[item]weapon.name}) hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257950, 'label': u'AttackHit2R_SimpleBody'}(u'<color=0xffbb6600>{source} hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257951, 'label': u'AttackHit2_SimpleBody'}(u'<color=0xff66bb00>{[item]weapon.name} hits {target} for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257952, 'label': u'AttackHit3RD_SimpleBody'}(u'<color=0xffbb6600>{owner} ({[item]weapon.name}) hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257953, 'label': u'AttackHit3R_SimpleBody'}(u'<color=0xffbb6600>{source} hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257954, 'label': u'AttackHit3_SimpleBody'}(u'<color=0xff99bb00>{[item]weapon.name} hits {target} for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257955, 'label': u'AttackHit4RD_SimpleBody'}(u'<color=0xffbb6600>{owner} ({[item]weapon.name}) hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257956, 'label': u'AttackHit4R_SimpleBody'}(u'<color=0xffbb6600>{source} hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257958, 'label': u'AttackHit5RD_SimpleBody'}(u'<color=0xffbb6600>{owner} ({[item]weapon.name}) hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257959, 'label': u'AttackHit5R_SimpleBody'}(u'<color=0xffbb6600>{source} hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257960, 'label': u'AttackHit5_SimpleBody'}(u'<color=0xff99bb00>{[item]weapon.name} hits {target} for <b>{[numeric]damage,decimalPlaces=0}</b> damage', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257961, 'label': u'AttackHit6RD_SimpleBody'}(u'<color=0xffbb6600>{owner} ({[item]weapon.name}) hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage (Wrecking!)', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 257962, 'label': u'AttackHit6R_SimpleBody'}(u'<color=0xffbb6600>{source} hits you for <b>{[numeric]damage,decimalPlaces=0}</b> damage (Wrecking!)', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage,decimalPlaces=0}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 0}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258022, 'label': u'AttackMiss1_SimpleBody'}(u'{[item]weapon.name} misses {target}', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258044, 'label': u'AttackMiss1RD_SimpleBody'}(u'{owner} ({[item]weapon.name}) misses you', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258045, 'label': u'AttackMiss1R_SimpleBody'}(u'{source} misses you', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258046, 'label': u'AttackMiss2RD_SimpleBody'}(u'{owner} ({[item]weapon.name}) misses you', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258047, 'label': u'AttackMiss3_SimpleBody'}(u'{[item]weapon.name} misses {target}', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258048, 'label': u'AttackMiss3R_SimpleBody'}(u'{source} misses you', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258049, 'label': u'AttackMiss2_SimpleBody'}(u'{[item]weapon.name} misses {target}', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258050, 'label': u'AttackMiss2R_SimpleBody'}(u'{source} misses you', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}})
 * {'FullPath': u'UI/Messages', 'messageID': 258051, 'label': u'AttackMiss3RD_SimpleBody'}(u'{owner} ({[item]weapon.name}) misses you', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260383, 'label': u'AttackHit1Body'}(u'<color=0xffbbbb00>Your {[item]weapon.name} barely scratches {target}, causing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260385, 'label': u'AttackHit1RBody'}(u'<color=0xffbb6600>{source} barely scratches you, causing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260386, 'label': u'AttackHit1RDBody'}(u'<color=0xffbb6600>{[item]weapon.name} belonging to {owner} barely scratches you, causing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260387, 'label': u'AttackHit2Body'}(u'<color=0xffbbbb00>Your {[item]weapon.name} lightly hits {target}, doing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260388, 'label': u'AttackHit2RBody'}(u'<color=0xffbb6600>{source} lightly hits you, doing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260390, 'label': u'AttackHit2RDBody'}(u'<color=0xffbb6600>{[item]weapon.name} belonging to {owner} lightly hits you, doing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260391, 'label': u'AttackHit3Body'}(u'<color=0xffbbbb00>Your {[item]weapon.name} hits {target}, doing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260392, 'label': u'AttackHit3RBody'}(u'<color=0xffbb6600>{source} hits you, doing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260393, 'label': u'AttackHit3RDBody'}(u'<color=0xffbb6600>{[item]weapon.name} belonging to {owner} hits you, doing {[numeric]damage, decimalPlaces=1} damage.', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260394, 'label': u'AttackHit4Body'}(u'<color=0xffbbbb00>Your {[item]weapon.name} is well aimed at {target}, inflicting {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260395, 'label': u'AttackHit4RBody'}(u'<color=0xffbb6600>{source} aims well at you, inflicting {[numeric]damage, decimalPlaces=1} damage.', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260396, 'label': u'AttackHit4RDBody'}(u'<color=0xffbb6600>{[item]weapon.name} belonging to {owner} heavily hits you, inflicting {[numeric]damage, decimalPlaces=1} damage.', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260397, 'label': u'AttackHit5Body'}(u'<color=0xffbbbb00>Your {[item]weapon.name} places an excellent hit on {target}, inflicting {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260398, 'label': u'AttackHit5RBody'}(u'<color=0xffbb6600>{source} places an excellent hit on you, inflicting {[numeric]damage, decimalPlaces=1} damage.', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260399, 'label': u'AttackHit5RDBody'}(u'<color=0xffbb6600>{[item]weapon.name} belonging to {owner} places an excellent hit on you, inflicting {[numeric]damage, decimalPlaces=1} damage.', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260400, 'label': u'AttackHit6Body'}(u'<color=0xffbbbb00>Your {[item]weapon.name} perfectly strikes {target}, wrecking for {[numeric]damage, decimalPlaces=1} damage.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260401, 'label': u'AttackHit6RBody'}(u'<color=0xffbb6600>{source} strikes you perfectly, wrecking for {[numeric]damage, decimalPlaces=1} damage.', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260402, 'label': u'AttackHit6RDBody'}(u'<color=0xffbb6600>{[item]weapon.name} belonging to {owner} strikes you perfectly, wrecking for {[numeric]damage, decimalPlaces=1} damage.', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}, u'{[numeric]damage, decimalPlaces=1}': {'conditionalValues': [], 'variableType': 9, 'propertyName': None, 'args': 512, 'kwargs': {'decimalPlaces': 1}, 'variableName': 'damage'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260410, 'label': u'AttackMiss1Body'}(u'Your {[item]weapon.name} misses {target} completely.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260411, 'label': u'AttackMiss1RBody'}(u'{source} misses you completely.', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260412, 'label': u'AttackMiss1RDBody'}(u'{[item]weapon.name} belonging to {owner} misses you completely.', None, {u'{owner}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'owner'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260413, 'label': u'AttackMiss2Body'}(u'Your {[item]weapon.name} barely misses {target}.', None, {u'{target}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'target'}, u'{[item]weapon.name}': {'conditionalValues': [], 'variableType': 2, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'weapon'}})
 * {'FullPath': u'UI/Messages', 'messageID': 260414, 'label': u'AttackMiss2RBody'}(u'{source} barely misses you.', None, {u'{source}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'source'}})
 *
 */

namespace Dmg {

    namespace Msg {

        static const char* Self[7] = {
            "AttackMiss1R",   //miss
            //AttackMiss1Banked  ?not sure here....'banked' means 'group weapons'  also in ship.modules.GetTurretSets in MakeSlimItem()
            "AttackHit1R",    //barely scratches
            "AttackHit2R",    //lightly hits
            "AttackHit3R",    //hits
            "AttackHit4R",    //aims well at you
            "AttackHit5R",    //places an excellent hit
            "AttackHit6R"     //strikes you perfectly, wrecking
        };

        static const char* Named[7] = {
            "AttackMiss1RD",   //miss
            "AttackHit1RD",    //barely scratches
            "AttackHit2RD",    //lightly hits
            "AttackHit3RD",    //hits
            "AttackHit4RD",    //aims well at you
            "AttackHit5RD",    //places an excellent hit
            "AttackHit6RD"     //strikes you perfectly, wrecking
        };

        static const char* Other[7] = {
            "AttackMiss1",   //miss
            "AttackHit1",    //barely scratches
            "AttackHit2",    //lightly hits
            "AttackHit3",    //hits
            "AttackHit4",    //aims well
            "AttackHit5",    //places an excellent hit
            "AttackHit6"     //strikes perfectly, wrecking
        };
    }
}

/*
 *    def OnDamageMessage(self, msgKey, args):
 *        try:
 *            michelle = sm.GetService('michelle')
 *            hitQuality = 0
 *            if msgKey.startswith('AttackHit'):
 *                try:
 *                    hitQuality = int(msgKey[9])
 *                except ValueError as e:
 *                    hitQuality = 5
 *
 *            banked = msgKey.find('Banked') > 0
 *            if args.has_key('target'):
 *                ship = michelle.GetBall(session.shipid)
 *                if ship and hasattr(ship, 'turrets'):
 *                    self.DamageMessageTurretPropogation(session.shipid, ship, hitQuality, args, banked)
 *            elif args.has_key('owner'):
 *                ownerData, ownerID = args['owner']
 *                targetSvc = sm.GetService('target')
 *                ship = None
 *                shipID = targetSvc.ownerToShipIDCache.get(ownerID, None)
 *                if shipID is not None:
 *                    ship = michelle.GetBall(shipID)
 *                else:
 *                    self.LogWarn('Turret hit/miss - failed to find shipID for ownerID ' + str(ownerID))
 *                if shipID and ship:
 *                    self.DamageMessageTurretPropogation(shipID, ship, hitQuality, args, banked)
 *            elif args.has_key('source'):
 *                shipID = args['source']
 *                ship = michelle.GetBall(shipID)
 *                if hasattr(ship, 'turrets'):
 *                    self.DamageMessageTurretPropogation(shipID, ship, hitQuality, args, banked)
 *                elif hasattr(ship, 'GetModel') and hasattr(ship.GetModel(), 'turretSets'):
 *                    self.DamageMessageGrouped(ship.GetModel().turretSets, hitQuality)
 *        except Exception as e:
 *            self.LogError('Error setting hit/miss state on a turret: %s %s' % (msgKey, str(args)))
 *            self.LogError(str(e) + ' ' + str(e.args))
 *
 *        if not settings.user.ui.Get('damageMessages', 1):
 *            return
 *        if args.has_key('damage') and args['damage'] == 0.0 and not settings.user.ui.Get('damageMessagesNoDamage', 1):
 *            return
 *        if args.has_key('owner') or args.has_key('source'):
 *            sm.ScatterEvent('OnShipDamage', args.get('damageTypes', {}))
 *            if not settings.user.ui.Get('damageMessagesEnemy', 1):
 *                return
 *        elif not settings.user.ui.Get('damageMessagesMine', 1):
 *            return
 *        if settings.user.ui.Get('damageMessagesSimple', 0):
 *            msgKey += '_Simple'
 *        for argName in ('source', 'target'):
 *            if args.has_key(argName):
 *                bracketName = sm.GetService('bracket').GetBracketName(args[argName])
 *                if not len(bracketName):
 *                    ballpark = sm.GetService('michelle').GetBallpark()
 *                    if ballpark is None:
 *                        self.LogWarn('OnDamageMessage: No ballpark, not showing damage message.')
 *                        return
 *                    slimItem = ballpark.GetInvItem(args[argName])
 *                    if slimItem:
 *                        bracketName = uix.GetSlimItemName(slimItem) or 'Some object'
 *                if not len(bracketName):
 *                    self.LogError('Failed to display message', msgKey, args)
 *                    return
 *                args[argName] = bracketName
 *
 *        msgKey = msgKey.replace('BankedR', 'R')
 *        sm.GetService('logger').AddCombatMessage(msgKey, args)
 */


#endif  // EVE_DAMAGE_H