

/*
 *
 * LSC stands for Large Scale Chat
 *
 *
 * CHTMODE_CREATOR = 8 + 4 + 2 + 1
 * CHTMODE_OPERATOR = 4 + 2 + 1
 * CHTMODE_CONVERSATIONALIST = 2 + 1
 * CHTMODE_SPEAKER = 2
 * CHTMODE_LISTENER = 1
 * CHTMODE_NOTSPECIFIED = -1
 * CHTMODE_DISALLOWED = -2
 * CHTERR_NOSUCHCHANNEL = -3
 * CHTERR_ACCESSDENIED = -4
 * CHTERR_INCORRECTPASSWORD = -5
 * CHTERR_ALREADYEXISTS = -6
 * CHTERR_TOOMANYCHANNELS = -7
 * CHT_MAX_USERS_PER_IMMEDIATE_CHANNEL = 50
 * CHT_MAX_INPUT = 253
 *
 *
 *  'rookieHelpChannel': 1,
 *  'helpChannelEN': 2,
 *  'helpChannelDE': 40,
 *  'helpChannelRU': 55,
 *  'helpChannelJA': 56
 *
 */
